sudo: required
language: node_js
node_js:
  - 6
  - 4
services:
  - docker
before_install:
  - docker pull influxdb
  - docker run -d -p 8083:8083 -p 8086:8086 influxdb
script: npm run test:travis

after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
