language: node_js
node_js:
  - "4.1"
  - "0.12"
  - "0.10"
env:
  - INFLUX=0.9.1-rc1
before_script:
  - wget "http://s3.amazonaws.com/influxdb/influxdb_$(echo $INFLUX)_amd64.deb"
  - sudo dpkg -i "influxdb_$(echo $INFLUX)_amd64.deb"
  - sudo openssl req -new -newkey rsa:4096 -days 3650 -nodes -x509 -subj '/C=US/ST=NewYork/L=NYC/O=Influx/CN=*' -keyout /server.pem -out /server.pem >/dev/null 2>&1

  - sudo service influxdb start
  - sleep 5
script: npm run travis-test
after_script:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls && rm -rf ./coverage
